baseurl = "/"
languageCode = "en-us"
title = "Mundoreves"
copyright = "Dimitris Rudas"
canonifyurls = true
theme = "ghostwriter"

publishdir = "public"

[Author]
	name = "dimitrisr"

[[menu.main]]
	name = "Portfolio"
	url = "/portfolio/"
	weight = 1

[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2

[[menu.main]]
	name = "Blog"
	url = "/blog/"
	weight = 3

[[menu.main]]
	name = "Contact"
	url = "/contact/"
	weight = 4

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[taxonomies]
	tag = "tags"
	topic = "topics"